[tool.ruff]
line-length = 99  
lint.select = ["ALL", "E402"]  
lint.ignore = ["D100"] 
lint.extend-select = ["I"] 
fix = true

[tool.pyright]
reportUnknownMemberType = "none"
reportUnknownArgumentType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportPrivateImportUsage = "none"
reportMissingTypeStubs = false
